version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html

  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18888:8888"
    volumes:
      - ./public/web:/var/app
