version: "3"
services:
  # web:
  #   tty: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "18888:8888"
  #   volumes:
  #     - ./public/web:/var/app
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html

  postgresql:
    image: postgres:13.4
    ports:
      - 5433:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
